# Generated by Django 5.1.6 on 2025-02-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kategoriya',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('slug', models.SlugField(max_length=100)),
                ('xolati', models.CharField(choices=[('QORALAMA', 'QORALAMA'), ('Chop Etish', 'CHOP ETISH')], default='QORALAMA', max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.kategoriya')),
            ],
            options={
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
