# Generated by Django 4.2.18 on 2025-01-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Janri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Janri')),
            ],
            options={
                'verbose_name_plural': 'Janri',
            },
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='<FISH')),
            ],
            options={
                'verbose_name_plural': 'Mallif',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='<Nomi')),
                ('sahifalar', models.IntegerField(default=1, verbose_name='Sahifalar')),
                ('janri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.janri')),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.muallif')),
            ],
            options={
                'verbose_name_plural': 'Book',
            },
        ),
    ]
